#!/bin/bash

set -e
#set the DEBUG env variable to turn on debugging
[[ -n "$DEBUG" ]] && set -x

# Environment
export HAPROXY_DOMAIN=${HAPROXY_DOMAIN:-router.local}

export CONSUL_LOGLEVEL=${CONSUL_LOGLEVEL:-warn}
export CONSUL_MINWAIT=${CONSUL_MINWAIT:-2s}
export CONSUL_MAXWAIT=${CONSUL_MAXWAIT:-10s}
export CONSUL_URL=${CONSUL_URL:-consul:8500}

function usage {
cat <<USAGE
  router                  Start a router container built on haproxy,
                          dnsmasq, and consul-template

  Configure using the following environment variables:

  haproxy variables:

    HAPROXY_DOMAIN        Domain for HAProxy routing
                          (default router.local)

  consul-template variables:

    CONSUL_URL            The consul connection
                          (default consul:8500)

    CONSUL_LOGLEVEL       Valid values are "debug", "info", "warn", and "err".
                          (default is "warn")

    CONSUL_MINWAIT        Minimum value to wait for consul
                          (default is "2s")

    CONSUL_MAXWAIT        Maximum value to wait for consul
                          (default is "10s")

    CONSUL_TOKEN		      Consul ACL token to use
                          (default is not set)

  More detailed configuration can be achieved by overwriting any of
  the default configuration files/templates located at:

    - /router/dnsmasq.cfg
    - /router/dnsmasq.hosts.tmpl
    - /router/dnsmasq.servers.tmpl
    - /router/consul.cfg
    - /router/haproxy.cfg.tmpl

  Additional arguments passed in will be forwarded directly to consul-template

USAGE
}

touch /var/log/haproxy.log
touch /var/log/dnsmasq.log
touch /var/log/messages

tail -f /var/log/haproxy.log &
tail -f /var/log/dnsmasq.log &
tail -f /var/log/messages &

if [ "$(ls -A /usr/local/share/ca-certificates)" ]; then
  cat /usr/local/share/ca-certificates/* >> /etc/ssl/certs/ca-certificates.crt
fi

if [ -n "${CONSUL_TOKEN}" ]; then
  export CONSUL_TOKEN_ARG="${CONSUL_TOKEN_ARG} -token ${CONSUL_TOKEN}"
fi

export CONSUL_EXTRA_ARGS=$@

rsyslogd
/usr/sbin/haproxy -D -p /var/run/haproxy.pid -f /router/haproxy.cfg -sf $(cat /var/run/haproxy.pid)
/usr/sbin/dnsmasq -C /router/dnsmasq.cfg
/usr/local/bin/consul-template -config /router/consul.cfg -log-level ${CONSUL_LOGLEVEL} -wait ${CONSUL_MINWAIT}:${CONSUL_MAXWAIT} -consul ${CONSUL_URL} ${CONSUL_TOKEN_ARG} ${CONSUL_EXTRA_ARGS}
